services:
  backend:
    container_name: tic-tac-toe-backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5010:5000"
  frontend:
    container_name: tic-tac-toe-frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3011:3000"
    depends_on:
      - backend

  proxy:
    image: nginx:1.21-alpine
    container_name: tic-tac-toe-proxy
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend
      - frontend